### ISSUE TITLE
pydantic library update breaks config

### ISSUE THREAD

**Issue by reisingerf** [aehrc/serverless-beacon#80]
We got the following errors after updating to the latest update (`master` branch).

```
/opt/python/pydantic/_internal/_config.py:257: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
```

Looks like the pydantic library has been updated and now causes a configuration mismatch.
See release notes: https://docs.pydantic.dev/2.0/migration/

As workaround the pydantic version could be pinned to: v1.10.11
As general best practise one could consider pinning all dependency versions.

Note: I had a little trouble finding the dependency management inside the `init.sh` script as I was looking for a `requirements.txt` file.

**Comment by victorskl** [comment]
I'd recommend pin versions to dependencies, yes.
ping @anuradhawick
